m4-w10-history-geek/src/main/java/com/techelevator/model/DollarAmount.java
package com.techelevator.model;

import java.math.BigDecimal;
import java.math.RoundingMode;

public class DollarAmount {

	public static final DollarAmount ZERO_DOLLARS = new DollarAmount(0);

	private long totalAmountInCents;

	public DollarAmount(int totalAmountInCents) {
		this.totalAmountInCents = totalAmountInCents;
	}

	public DollarAmount(long totalAmountInCents) {
		this.totalAmountInCents = totalAmountInCents;
	}
	
	public DollarAmount(BigDecimal amount) {
		BigDecimal oneHundred = new BigDecimal("100");
		this.totalAmountInCents = amount.multiply(oneHundred).intValue();
	}

	public boolean isGreaterThan(DollarAmount amountToCompare) {
		return this.totalAmountInCents > amountToCompare.totalAmountInCents;
	}

	public boolean isGreaterThanOrEqualTo(DollarAmount amountToCompare) {
		return this.totalAmountInCents >= amountToCompare.totalAmountInCents;
	}

	public boolean isLessThan(DollarAmount amountToCompare) {
		return this.totalAmountInCents < amountToCompare.totalAmountInCents;
	}

	public boolean isLessThanOrEqualTo(DollarAmount amountToCompare) {
		return this.totalAmountInCents <= amountToCompare.totalAmountInCents;
	}

	public boolean isNegative() {
		return totalAmountInCents < 0;
	}

	public DollarAmount minus(DollarAmount amountToSubtract) {
		return new DollarAmount(this.totalAmountInCents - amountToSubtract.totalAmountInCents);
	}

	public DollarAmount plus(DollarAmount amountToAdd) {
		return new DollarAmount(this.totalAmountInCents + amountToAdd.totalAmountInCents);
	}

	public DollarAmount multipliedBy(long multiplier) {
		return new DollarAmount(totalAmountInCents * multiplier);
	}

	public DollarAmount multipliedBy(double multiplier) {
		return new DollarAmount(getBigDecimalValue().multiply(new BigDecimal(multiplier)));
	}
	
	/**
	 * Will truncate fractional cents.
	 * 
	 * @param divisor
	 * @return
	 */
	public DollarAmount dividedBy(long divisor) {
		return new DollarAmount(totalAmountInCents / divisor);
	}
	
	public BigDecimal getBigDecimalValue() {
		return new BigDecimal(toDecimalString()).setScale(2, RoundingMode.DOWN);
	}

	private String toDecimalString() {
		long dollars = totalAmountInCents / 100;
		int cents = (int)(totalAmountInCents % 100);
		String centsString = cents >= 10 ? String.valueOf(cents) : "0"+String.valueOf(cents);
		String decimalString = String.valueOf(dollars) + "." + centsString;
		return decimalString;
	}

	public int compareTo(DollarAmount amountToCompare) {
		if (this.isGreaterThan(amountToCompare)) {
			return 1;
		} else if (this.isLessThan(amountToCompare)) {
			return -1;
		} else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj != null && obj instanceof DollarAmount) {
			return this.totalAmountInCents == ((DollarAmount) obj).totalAmountInCents;
		} else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return new Long(totalAmountInCents).hashCode();
	}

	@Override
	public String toString() {
		return "$"+toDecimalString();
	}
}

m4-w10-history-geek/src/main/java/com/techelevator/model/Order.java
package com.techelevator.model;

import static com.techelevator.model.DollarAmount.ZERO_DOLLARS;

import java.util.Map;

public class Order {

	private Long id;
	private Long userID;
	private String nameOnCard;
	private String creditCardNumber;
	private String expirationDate;
	private String billingAddress1;
	private String billingAddress2;
	private String billingCity;
	private String billingState;
	private String billingPostalCode;
	private String shippingAddress1;
	private String shippingAddress2;
	private String shippingCity;
	private String shippingState;
	private String shippigPostalCode;
	private String shippingType;
	private DollarAmount subTotal = ZERO_DOLLARS;
	private double weight;
	private DollarAmount shipping = ZERO_DOLLARS;
    private DollarAmount tax = ZERO_DOLLARS;
    private Map<String, DollarAmount> shippingRates;
    
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public Long getUserID() {
		return userID;
	}
	public void setUserID(Long userID) {
		this.userID = userID;
	}
	//Required
	public String getNameOnCard() {
		return nameOnCard;
	}
	public void setNameOnCard(String nameOnCard) {
		this.nameOnCard = nameOnCard;
	}
	//Required
	public String getCreditCardNumber() {
		return creditCardNumber;
	}
	public void setCreditCardNumber(String creditCardNumber) {
		this.creditCardNumber = creditCardNumber;
	}
	//Required
	public String getExpirationDate() {
		return expirationDate;
	}
	public void setExpirationDate(String expirationDate) {
		this.expirationDate = expirationDate;
	}
	//Required
	public String getBillingAddress1() {
		return billingAddress1;
	}
	public void setBillingAddress1(String billingAddress1) {
		this.billingAddress1 = billingAddress1;
	}
	public String getBillingAddress2() {
		return billingAddress2;
	}
	public void setBillingAddress2(String billingAddress2) {
		this.billingAddress2 = billingAddress2;
	}
	//Required
	public String getBillingCity() {
		return billingCity;
	}
	public void setBillingCity(String billingCity) {
		this.billingCity = billingCity;
	}
	//Required
	public String getBillingState() {
		return billingState;
	}
	public void setBillingState(String billingState) {
		this.billingState = billingState;
	}
	//Required
	public String getBillingPostalCode() {
		return billingPostalCode;
	}
	public void setBillingPostalCode(String billingPostalCode) {
		this.billingPostalCode = billingPostalCode;
	}
	//Required
	public String getShippingAddress1() {
		return shippingAddress1;
	}
	public void setShippingAddress1(String shippingAddress1) {
		this.shippingAddress1 = shippingAddress1;
	}
	public String getShippingAddress2() {
		return shippingAddress2;
	}
	public void setShippingAddress2(String shippingAddress2) {
		this.shippingAddress2 = shippingAddress2;
	}
	//Required
	public String getShippingCity() {
		return shippingCity;
	}
	public void setShippingCity(String shippingCity) {
		this.shippingCity = shippingCity;
	}
	//Required
	public String getShippingState() {
		return shippingState;
	}
	public void setShippingState(String shippingState) {
		this.shippingState = shippingState;
	}
	//Required
	public String getShippingPostalCode() {
		return shippigPostalCode;
	}
	public void setShippingPostalCode(String shippingPostalCode) {
		this.shippigPostalCode = shippingPostalCode;
	}
	//Required
	public String getShippingType() {
		return shippingType;
	}
	public void setShippingType(String shippingType) {
		this.shippingType = shippingType;
	}
	public DollarAmount getSubTotal() {
		return subTotal;
	}
	public void setSubTotal(DollarAmount subTotal) {
		this.subTotal = subTotal;
	}
	public double getWeight() {
		return weight;
	}
	public void setWeight(double weight) {
		this.weight = weight;
	}
	public DollarAmount getShipping() {
		return shipping;
	}
	public void setShipping(DollarAmount shipping) {
		this.shipping = shipping;
	}
	public DollarAmount getTax() {
		return tax;
	}
	public void setTax(DollarAmount tax) {
		this.tax = tax;
	}
	public DollarAmount getTotal() {
		return subTotal.plus(shipping).plus(tax);
	}
	public Map<String, DollarAmount> getShippingRates() {
		return shippingRates;
	}
	public void setShippingRates(Map<String, DollarAmount> shippingRates) {
		this.shippingRates = shippingRates;
	}

}

m4-w10-history-geek/src/main/java/com/techelevator/controller/StoreController.java
package com.techelevator.controller;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.SessionAttributes;

import com.techelevator.calculator.ShippingCalculator;
import com.techelevator.calculator.TaxCalculator;
import com.techelevator.model.Order;
import com.techelevator.model.OrderDAO;
import com.techelevator.model.OrderItem;
import com.techelevator.model.OrderItemDAO;
import com.techelevator.model.Product;
import com.techelevator.model.ProductDAO;
import com.techelevator.model.ShoppingCart;
import com.techelevator.model.ShoppingCartItem;
import com.techelevator.model.User;
import com.techelevator.model.UserDAO;
import com.techelevator.model.viewmodel.ConfirmationViewModel;

@Controller
@SessionAttributes({"shoppingCart", "email"})
public class StoreController {

    private ProductDAO productDAO;
    private OrderDAO orderDAO;
    private OrderItemDAO orderItemDAO;
    private UserDAO userDAO;

    @Autowired
    public StoreController(ProductDAO oroductDAO, OrderDAO orderDAO, OrderItemDAO orderItemDAO, UserDAO userDAO) {
        this.productDAO = oroductDAO;
        this.orderDAO = orderDAO;
        this.orderItemDAO = orderItemDAO;
        this.userDAO = userDAO;
    }

	@RequestMapping(path="/store")
    public String getStore(ModelMap model) {
		model.addAttribute("products", productDAO.getProducts());
        return "store/getStore";
    }

	@RequestMapping(path="/store/detail/{sku}")
    public String listProductsl(@PathVariable String sku, ModelMap model) {
        Product product = productDAO.getProduct(sku);
//        if (model == null)
//        {
//            return new HttpNotFoundResult();
//        }
        model.addAttribute(product);
        return "store/detail";
    }

	@RequestMapping(path="/store/addToCart", method=RequestMethod.POST)
    public String addToCart(@RequestParam String sku, @RequestParam int quantity, ModelMap model) {
        Product product = productDAO.getProduct(sku);
//        if (product == null || quantity < 1)
//        {
//            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
//        }
        ShoppingCart cart = getActiveShoppingCart(model);
        cart.addToCart(product, quantity);
        return "redirect:/store/viewCart";
    }

	@RequestMapping(path="/store/updateCart", method=RequestMethod.POST)
	public String updateCart(@RequestParam String sku, @RequestParam int quantity, ModelMap model) {
        // Update the quantity of an item in the cart
        ShoppingCart cart = getActiveShoppingCart(model);
        if (quantity <= 0) {
            List<ShoppingCartItem> sciList = cart.getItems();
            for (int i = sciList.size() -1; i >= 0; i--) {
				if (sciList.get(i).getProduct().getSku().equals(sku)) {
					sciList.remove(i);
					break;
				}
            }
        }
        else {
            List<ShoppingCartItem> sciList = cart.getItems();
            for (int i = 0; i < sciList.size(); i++) {
				if (sciList.get(i).getProduct().getSku().equals(sku)) {
					sciList.get(i).setQuantity(quantity);
					break;
				}
            }
        }
        return "redirect:/store/viewCart";
    }

	@RequestMapping(path="/store/checkout")
    public String checkout(ModelMap model) {
        // If the user has not logged in yet, make them log in
        if(model.get("email") == null) {
            return "redirect:/user/login";
        }

        ShoppingCart cart = getActiveShoppingCart(model);

        //If they don't have any items, redirect them to ViewCart
        if (cart.getItems().size() == 0) {
            return "redirect:/store/viewCart";
        }

        //Create an Order Model that sums up the item totals and weights
        Order order = new Order();
        order.setSubTotal(cart.getSubTotal());
        double weight = 0;
        for(ShoppingCartItem sci : cart.getItems() ) {
        	weight += sci.getWeight();
        }
        order.setWeight(weight);

        //Set the shipping rates to use for the model
        order.setShippingRates(ShippingCalculator.getShippingRates(order.getWeight()));
        model.addAttribute("order", order);
        return "store/checkout";
    }

	@RequestMapping(path = "/store/checkout", method = RequestMethod.POST)
	public String checkout(HttpSession session, Order order, ModelMap model) {
		// Get their active shopping cart
		ShoppingCart cart = getActiveShoppingCart(model);
		order.setSubTotal(cart.getSubTotal());
		double weight = 0;
		for (ShoppingCartItem sci : cart.getItems()) {
			weight += sci.getWeight();
		}
		order.setWeight(weight);

		// if (!ModelState.IsValid)
		// {
		// order.ShippingRates =
		// ShippingCalculator.GetShippingRates(order.Weight);
		// return View("Checkout", order);
		// }

		// Update the order with fields from the customer's checkout
		order.setTax(cart.getSubTotal().multipliedBy(TaxCalculator.getTaxRate(order.getBillingPostalCode())));
		order.setShipping(ShippingCalculator.getShippingRates(order.getWeight()).get(order.getShippingType()));
		User user = userDAO.getUser(model.get("email").toString());
		order.setUserID(user.getID());

		// Create a transaction to save these in the database
		// We want to make sure that the order is saved, along with each order
		// item
		// using (TransactionScope tran = new TransactionScope()) {
		// //Save the Order
		orderDAO.saveOrder(order);

		// Convert each "ShopingCartItem" to an "OrderItem" and give it the new
		// order id
		List<OrderItem> orderItems = new ArrayList<>();
		for (ShoppingCartItem sci : cart.getItems()) {
			OrderItem oi = new OrderItem();
			oi.setPrice(sci.getPrice());
			oi.setProductID(sci.getProduct().getId());
			oi.setQuantity(sci.getQuantity());
			oi.setOrderID(order.getId());
			orderItems.add(oi);
		}

		// Save the Order Items
		orderItemDAO.saveOrderItems(orderItems);

		// Empty the shopping cart
		cart.empty();
		//
		// //Save the transaction
		// tran.Complete();
		// }
		return "redirect:/store/confirm/" + order.getId();
	}

	@RequestMapping(path = "/store/confirm/{orderID}")
	public String confirm(@PathVariable Long orderID, ModelMap model) {
		// Build the view model and use the order, order items, and product
		// purchased to populate it
		ConfirmationViewModel confirmationViewModel = new ConfirmationViewModel();
		confirmationViewModel.setOrder(orderDAO.getOrder(orderID));
		confirmationViewModel.setOrderItems(orderItemDAO.getOrderItems(orderID));
		List<Product> products = new ArrayList<>();
		for (OrderItem oi : confirmationViewModel.getOrderItems()) {
			products.add(productDAO.getProductByID(oi.getProductID()));
		}
		confirmationViewModel.setProducts(products);
		model.addAttribute("confirmationViewModel", confirmationViewModel);
		return "/store/confirm";
	}

	@RequestMapping(path="/store/viewCart")
    public String viewCart(ModelMap model) {
        return "/store/viewCart";
    }

    private ShoppingCart getActiveShoppingCart(ModelMap model) {
        if (model.get("shoppingCart") == null) {
            model.addAttribute("shoppingCart", new ShoppingCart());
        }
        return (ShoppingCart)model.get("shoppingCart");
    }

}

m4-w10-history-geek/src/main/webapp/WEB-INF/jsp/store/checkout.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<c:import url="/WEB-INF/jsp/common/header.jsp" />

<h2>Complete your checkout</h2>
<div id="errorSummary">
	<h3>You have the following errors: </h3>
	<ul id="errors"></ul>
</div>
 
 <c:url var="formAction" value="/store/checkout" />
<form action="${formAction}" id="checkout" method="post"> 
	<fieldset id="billing-info">
		<h3>Billing Address</h3>
		<input id="BillingAddress1" name="BillingAddress1" placeholder="address" type="text" value="" />
		<input id="BillingAddress2" name="BillingAddress2" placeholder="apt., suite, company" type="text" value="" />
		<input id="BillingCity" name="BillingCity" placeholder="city" type="text" value="" />
		<input id="BillingState" name="BillingState" placeholder="state" type="text" value="" />
		<input id="BillingPostalCode" name="BillingPostalCode" placeholder="zip code" type="text" value="" />
		<input id="SameShipping" name="SameShipping" type="checkbox" value="true" />
		<input name="SameShipping" type="hidden" value="false" /><label>My shipping address is the same</label>
		<h3>Shipping Address</h3>
		<input id="ShippingAddress1" name="ShippingAddress1" placeholder="address" type="text" value="" />
		<input id="ShippingAddress2" name="ShippingAddress2" placeholder="apt., suite, company" type="text" value="" />
		<input id="ShippingCity" name="ShippingCity" placeholder="city" type="text" value="" />
		<input id="ShippingState" name="ShippingState" placeholder="state" type="text" value="" />
		<input id="ShippingPostalCode" name="ShippingPostalCode" placeholder="zip code" type="text" value="" />
	</fieldset>
	<fieldset id="shipping-info">
		<h3>Shipping Method</h3>
		<p><input data-cost="${order.shippingRates['Standard'].bigDecimalValue}" id="ShippingType" name="ShippingType" type="radio" value="Standard" /> <label>Standard Shipping: ${order.shippingRates['Standard']}</label></p>
		<p><input data-cost="${order.shippingRates['Express'].bigDecimalValue}" id="ShippingType" name="ShippingType" type="radio" value="Express" /> <label>Express Shipping: ${order.shippingRates['Express']}</label></p>
		<p><input data-cost="${order.shippingRates['Two-Day'].bigDecimalValue}" id="ShippingType" name="ShippingType" type="radio" value="Two-Day" /> <label>Two-Day Shipping: ${order.shippingRates['Two-Day']}</label></p>
		<p><input data-cost="${order.shippingRates['Overnight'].bigDecimalValue}" id="ShippingType" name="ShippingType" type="radio" value="Overnight" /> <label>Overnight Shipping: ${order.shippingRates['Overnight']}</label></p>
	</fieldset>
	<fieldset id="payment-info">
		<h3>Payment</h3>
		<input id="NameOnCard" name="NameOnCard" placeholder="name on card" type="text" value="" />
		<input id="CreditCardNumber" name="CreditCardNumber" placeholder="credit card" type="text" value="" />
		<input id="ExpirationDate" name="ExpirationDate" placeholder="mm/yy" type="text" value="" />
	</fieldset>
	<fieldset id="order-summary">
		<h3>Summary</h3>
		<p id="subtotal" class="attribute">Subtotal: <span class="price">${order.subTotal}</span></p>
		<p id="tax" class="attribute">Tax: <span class="price">${order.tax}</span></p>
		<p id="shipping" class="attribute">Shipping: <span class="price">${order.shipping}</span></p>
		<p id="grandtotal" class="attribute">Grand Total: <span class="price">${order.total}</span></p>
		<button>Complete Order</button>
	</fieldset>
	</form>
</form>

<c:import url="/WEB-INF/jsp/common/footer.jsp" />

m4-w10-history-geek/src/main/webapp/WEB-INF/jsp/store/confirm.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<c:import url="/WEB-INF/jsp/common/header.jsp" />

<div id="confirmation-page">
	<h2>Thank you for your order</h2>
	<p>Your items will be shipping soon.</p>
	<div id="order-data">
		<div id="shipping-info">
			<h4>Shipping Address</h4>
			<p>
				${confirmationViewModel.order.nameOnCard} <br />
				${confirmationViewModel.order.shippingAddress1} <br />
<%-- 				${confirmationViewModel.order.getCity() confirmationViewModel.order.getState(), confirmationViewModel.order.getPostalCode()} <br /> --%>
			</p>
		</div>
		<div id="payment-info">
			<h4>Payment Info</h4>
		</div>
		<div id="order-summary">
			<h4>Order Summary</h4>
			<div class="row">
				<span class="left">Item(s) Subtotal:</span> <span class="right">${confirmationViewModel.order.subTotal}</span>
			</div>
			<div class="row">
				<span class="left">Shipping &amp; Handling:</span> <span class="right">${confirmationViewModel.order.shipping}</span>
			</div>
			<div class="row">
				<span class="left">Tax:</span> <span class="right">${confirmationViewModel.order.tax}</span>
			</div>
			<div class="row">
				<span class="left">Grand Total:</span> <span class="right">${confirmationViewModel.order.total}</span>
			</div>
        	<c:url value="/store" var="storeHref" />
        	<p><a href="${storeHref}">Continue Shopping</a></p>
		</div>
	</div>
	<div id="order-items">
		<c:forEach var="product" items="${confirmationViewModel.products}">
		<tr>
			<div class="order-item">
				<div class="product-image">
				   	<c:url value="/img/products/" var="imgHref" />
			        <img src="${imgHref}${product.imageName}" title="${product.name}" />
				</div>
				<div class="product-data">
					<c:url value="/store" var="storeHref" />
					<a class="name" href="${storeHref}/detail/${product.sku}">${product.name}</a>

					<span class="price">$8.99</span>
					<span>Qty: 1</span>
					<form action="${storeHref}/addToCart?${product.sku}&amp;quantity=1" id="form0" method="post"> 
						<button>Buy again</button>
					</form>
				</div>
				<div class="product-actions">
					<button>Track package</button>
					<button>Return or replace item</button>
					<button>Get help with order</button>
				</div>
			</div>
		</tr>
		</c:forEach>
	
	</div>
</div>

<c:import url="/WEB-INF/jsp/common/footer.jsp" />

m4-w10-history-geek/src/main/webapp/WEB-INF/jsp/store/detail.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<c:import url="/WEB-INF/jsp/common/header.jsp" />

<div id="product-detail">
   	<c:url value="/img/products/" var="imgHref" />
	<div class="product-image">
        <img src="${imgHref}${product.imageName}" title="${product.name}" />
	</div>		
	<div class="product-data">
		<h3>${product.getName()}</h3>
		<p class="attribute">List Price: <span class="price">${product.price}</span></p>
		<p class="attribute">Weight: <span class="weight">${product.weight} oz</span></p>
		<p class="description">${product.description}</p>
	</div>
	<c:url var="formAction" value="/store/addToCart" />
	<form action="${formAction}" id="form0" method="post">
		<input id="sku" name="sku" type="hidden" value="${product.sku}" /> 
		<div>
			<select id="quantity" name="quantity">
				<option value="1">1</option>
				<option value="2">2</option>
				<option value="3">3</option>
				<option value="4">4</option>
				<option value="5">5</option>
				<option value="6">6</option>
			</select>
		</div>
		<button>Add To Cart</button>
	</form>
</div>

<c:import url="/WEB-INF/jsp/common/footer.jsp" />

m4-w10-history-geek/src/main/webapp/WEB-INF/jsp/store/getStore.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<c:import url="/WEB-INF/jsp/common/header.jsp" />

<h2>Gift Shop</h2>

<div id="products">
<c:forEach var="product" items="${products}">
	<div class="product-card">
    	<c:url value="/store/detail/" var="storeHref" />
    	<c:url value="/img/products/" var="imgHref" />
        <a href="${storeHref}${product.sku}"><img src="${imgHref}${product.imageName}" /></a>
		<a class="name" href="${storeHref}${product.sku}">
			${product.name}
		</a>
        <p class="price">${product.price}</p>
	</div>
</c:forEach>
</div>

<c:import url="/WEB-INF/jsp/common/footer.jsp" />

m4-w10-history-geek/src/main/webapp/WEB-INF/jsp/store/viewCart.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<c:import url="/WEB-INF/jsp/common/header.jsp" />

<div id="shopping-cart">
	<c:choose>
		<c:when test="${empty shoppingCart.items}">
			<h3>Your shopping cart is empty.</h3>
		</c:when>
		<c:otherwise>
			<table>
				<thead>
					<tr>
						<td></td>
						<td></td>
						<td>Price</td>
						<td>Quantity</td>
						<td>Subtotal</td>
					</tr>
				</thead>
				<c:forEach var="cartItem" items="${shoppingCart.items}">
					<tr>
						<td class="image">
						   	<c:url value="/img/products/" var="imgHref" />
					        <img src="${imgHref}${cartItem.product.imageName}" title="${product.name}" />
						</td>
						<td class="title">
							<c:url value="/store/detail" var="storeHref" />
							<h3><a class="name" href="${storeHref}/${cartItem.product.sku}">${cartItem.product.name}</a></h3>
						</td>
						<td class="price">
							${cartItem.product.price}
						</td>
						<td class="quantity">
							<c:url var="formAction" value="/store/updateCart" />
							<form action="${formAction}" id="form0" method="post">
								<input id="sku" name="sku" type="hidden" value="${cartItem.product.sku}" />
								<input id="quantity" name="quantity" type="number" value="${cartItem.quantity}" /> 
								<button>Update Cart</button>
							</form>
						</td>
						<td class="subtotal">
							${cartItem.price}
						</td>
					</tr>
				</c:forEach>
				<tr>
					<td colspan="5">
						<p>Total: <span class="price">${shoppingCart.subTotal}</span></p>
						<c:url value="/store/checkout" var="storeHref" />
						<a class="button" href="${storeHref}">Checkout</a>
					</td>
				</tr>
			</table>
		</c:otherwise>
	</c:choose>
</div>

<c:import url="/WEB-INF/jsp/common/footer.jsp" />